export const userList = [
    {
        id:1,
        firstName: "jacob",
        middleName: "Wills",
        lastName: "Wills",
        SSN: "37858",
        mobile: "9849492384",
        email: "jacob@gmail.com",
        gender: "male",
        DOB: "12-22-2022",
        designation: "developer",
        address: "times street",
        town: "NewYork",
        state: "USA",
        zipCode: "000"
    },
    {
        id:2,
        firstName: "steve",
        middleName: "smith",
        lastName: "smith",
        SSN: "93894859",
        mobile: "9849492384",
        email: "steve@gmail.com",
        gender: "male",
        DOB: "12-22-2022",
        designation: "developer",
        address: "times street",
        town: "NewYork",
        state: "USA",
        zipCode: "000"
    },
    {
        id:3,
        firstName: "henry",
        middleName: "cavil",
        lastName: "cavil",
        SSN: "9834975",
        mobile: "9849492384",
        email: "henry@gmail.com",
        gender: "male",
        DOB: "12-22-2022",
        designation: "developer",
        address: "times street",
        town: "NewYork",
        state: "USA",
        zipCode: "000"
    },
    {
        id:4,
        firstName: "jack",
        middleName: "Wick",
        lastName: "reacher",
        SSN: "9357575",
        mobile: "9849492384",
        email: "jack@gmail.com",
        gender: "male",
        DOB: "12-22-2022",
        designation: "developer",
        address: "times street",
        town: "NewYork",
        state: "USA",
        zipCode: "000"
    }
]